### PR TITLE
Install next runtime and update netlify/functions version

### PR DESCRIPTION
**Pull request by dwwoelfel**
Installs the next.js runtime and updates the @netlify/functions version.

### CODE REVIEW

**Comment by dwwoelfel** [comment]
Still one last thing that needs to be fixed on the Netlify side during the build. Working on that.

**Comment by colbyfayock** [comment]
thanks @dwwoelfel will merge this in, looking forward to getting in the final fixes 🙌

**Comment by dwwoelfel** [comment]
I forgot to update here, but the backend fixes went out on the 16th and all should be good now.

**Comment by colbyfayock** [comment]
thanks @dwwoelfel

**Pull request merged**
